version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./resume.db
    volumes:
      - .:/app
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
